# Generated by Django 4.1.3 on 2023-01-24 01:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10, verbose_name='ciclo')),
                ('paralelo', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=100)),
                ('duracion', models.FloatField(verbose_name='duración en horas')),
                ('estadoAsignatura', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Cuestionario Sin Nombre', max_length=150)),
                ('titulo', models.CharField(max_length=255)),
                ('encabezado', models.TextField()),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime.now, verbose_name='Inicio de la Encuesta')),
                ('fecha_fin', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fin de la Encuesta')),
                ('peso', models.IntegerField(default=1)),
                ('tipoInformante', models.CharField(choices=[('academico', 'Academico'), ('gestion', 'Gestion'), ('didactico', 'Didactico')], default='academico', max_length=15, verbose_name='TipoInformante')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='DirectivoAsignaturaDocente',
            fields=[
                ('directivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='directivo', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_directivo', models.BooleanField(default=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Directivo',
                'verbose_name_plural': 'Directivos',
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignaturaDocente',
            fields=[
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_docente', models.BooleanField(default=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='evaluacion.asignatura', verbose_name='Asignatura del docente')),
                ('cuestionarios', models.ManyToManyField(blank=True, to='evaluacion.cuestionario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='EstudianteAsignaturaDocente',
            fields=[
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('is_estudiante', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodoLectivo', models.CharField(db_column='periodo_lectivo', max_length=100)),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['fecha_inicio', 'fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.IntegerField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuestionarios', to='evaluacion.cuestionario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tabulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estTotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('docTotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dirTotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('estTotalSobre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('docTotalSobre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dirTotalSobre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('totalSobre', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('estTotalPon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('docTotalPon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dirTotalPon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('totalPon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.docenteasignaturadocente')),
            ],
            options={
                'verbose_name': 'Tabulacion',
                'verbose_name_plural': 'Tabulaciones',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('1', 'Opcion 1'), ('2', 'Opcion 2'), ('3', 'Opcion 3'), ('4', 'Opcion 4'), ('5', 'Opcion 5')], max_length=15, verbose_name='Respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_autorizacion', models.DateTimeField()),
                ('fecha_aprobacion', models.DateTimeField()),
                ('fecha_inicio_publicacion', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('periodoAcademico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='periodosEvaluacion', to='evaluacion.periodoacademico', verbose_name='Periodo Académico')),
            ],
            options={
                'verbose_name': 'Periodo Evaluación',
                'verbose_name_plural': 'Periodos de Evaluación',
                'ordering': ['fecha_inicio_publicacion', 'fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalEvaluacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario', to='evaluacion.cuestionario')),
                ('directivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_directivo', to='evaluacion.directivoasignaturadocente')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_docente', to='evaluacion.docenteasignaturadocente')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_estudiante', to='evaluacion.estudianteasignaturadocente')),
            ],
            options={
                'verbose_name': 'Evaluacion',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='directivoasignaturadocente',
            name='docente',
            field=models.ManyToManyField(blank=True, related_name='docenteD', to='evaluacion.docenteasignaturadocente', verbose_name='Directivo - Docente'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='periodoEvaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodoEvaluacion', to='evaluacion.periodoevaluacion', verbose_name='Periodo de Evaluación'),
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoAcademicoActual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='evaluacion.periodoacademico', verbose_name='Periodo Académico Actual')),
                ('periodoEvaluacionActual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='evaluacion.periodoevaluacion', verbose_name='Periodo Evaluación Actual')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='periodoAcademico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodoAcademico', to='evaluacion.periodoacademico', verbose_name='Periodo Académico'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.carrera'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cuestionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.cuestionario'),
        ),
    ]
